### ISSUE TITLE
Auto generated messages fail validation

### ISSUE THREAD

**Issue by stuart-xyz** [grundyoso/vleads#2]
Messages that are automatically generated upon a tag scan fail the Meteor `check` function that validates the contents as a string.

**Comment by grundyoso** [comment]
Could it be that the tag.data is an NSData object and needs to be converted to a NSString?  We have utilities in the Flomio SDK for these conversions..

**Comment by stuart-xyz** [comment]
This is an issue specific to the Meteor/Ionic app. By this point, the data has already been converted to a JavaScript string and passed into Meteor

**Comment by grundyoso** [comment]
hmm.. can you point me to the Meteor `check` call that is failing validation? what happens when you `console.log` the string from that location? do things look right? you could remove the `check` alltogether to get it to work?

**Comment by stuart-xyz** [comment]
@grundyoso I've tried removing the check but that didn't seem to solve the problem. `console.log` doesn't reveal any obvious problems. The code is located here:
https://github.com/grundyoso/vleads/blob/master/vleads/lib/methods.js#L8

**Comment by grundyoso** [comment]
hmm... I would try putting: 
`console.log("check this %s", message);`

the line right before and make sure it's happening at the right `check` call since there are many in that file:
https://github.com/grundyoso/vleads/blob/master/vleads/lib/methods.js#L7

you can see the server logs by running `mup logs -f` from your development box.. more details on that on this wiki post:
https://github.com/yummytech/flomio_apps_server/wiki/faq3%3A-How-to-get-Meteor-server-logs%3F

dump that it is that you're seeing on the server logs here so I can start to get my head around what's going on... also worth mentioning is the that files in the lib folder are actually executed both on the client and server so you should be able to find the file in Chrome Inspector and set breakpoints in the Meteor.method() calls to further see what is actually being received in the `message` variable.

**Comment by stuart-xyz** [comment]
I haven't been able to make any progress with this unfortunately. Appending `.toString()' to `chatId` [here](https://github.com/grundyoso/vleads/blob/master/vleads/client/scripts/controllers/nfc.controller.js#L76) resolves the validation failure, but no message is sent. The `message` variable looks fine and should not be any different to the variable that is sent from the [chat controller](https://github.com/grundyoso/vleads/blob/master/vleads/client/scripts/controllers/chat.controller.js). It's also worth mentioning that the [chat lookup](https://github.com/grundyoso/vleads/blob/master/vleads/client/scripts/controllers/nfc.controller.js#L57) does not work, which means that a new chat is created every time (instead of sending a message within an existing chat). I'm not sure why this is happening since the `Chats` collection has global Meteor scope and `Session.get('nfcContact').toString()` also seems to be valid

**Comment by stuart-xyz** [comment]
@grundyoso By the way, this issue doesn't produce any server messages

**Comment by stuart-xyz** [comment]
This was resolved by removing an [erroneous Mongo DB search parameter](https://github.com/grundyoso/vleads/blob/1eb74779383c0542eaab84eb87ecc109365af901/vleads/client/scripts/controllers/nfc.controller.js#L57) (type: 'chat') and fixing the syntax of a [Meteor method callback function](https://github.com/grundyoso/vleads/blob/1eb74779383c0542eaab84eb87ecc109365af901/vleads/client/scripts/controllers/nfc.controller.js#L62).

**Comment by grundyoso** [comment]
This was a crappy bug that may have slowed momentum but I'm ecstatic that you were able to overcome it.
